-- --- PHẦN 1: CẤU HÌNH CƠ BẢN ---

-- 1. Bật tính năng bản đồ (PostGIS) cho Database
create extension if not exists postgis;

-- --- PHẦN 2: TẠO BẢNG DỮ LIỆU GỐC ---

-- 2. Tạo bảng chứa địa điểm du lịch
create table if not exists tourist_spots (
  id bigint generated by default as identity primary key,
  name text not null,               -- Tên địa điểm
  description text,                 -- Mô tả
  category text,                    -- Loại hình (công viên, đồ ăn...)
  image_url text,                   -- Link ảnh
  location geography(POINT)         -- Cột lưu tọa độ gốc (Dạng nhị phân, khó đọc)
);

-- 3. Thêm dữ liệu mẫu (Hà Nội)
-- Lưu ý: Dùng insert ignore hoặc kiểm tra để tránh trùng lặp nếu chạy nhiều lần
insert into tourist_spots (name, description, category, location)
values
  (
    'Hồ Gươm',
    'Trái tim của thủ đô Hà Nội, nơi có Tháp Rùa cổ kính.',
    'park',
    st_point(105.8521, 21.0285)
  ),
  (
    'Lăng Chủ tịch Hồ Chí Minh',
    'Nơi an nghỉ vĩnh hằng của Bác Hồ.',
    'culture',
    st_point(105.8342, 21.0368)
  ),
  (
    'Nhà thờ Lớn Hà Nội',
    'Công trình kiến trúc Pháp cổ kính.',
    'culture',
    st_point(105.8493, 21.0288)
  );

-- 4. Bật bảo mật cho bảng (Để người lạ không xóa được dữ liệu)
alter table tourist_spots enable row level security;

create policy "Cho phép ai cũng xem được"
on tourist_spots for select
to anon, authenticated
using (true);

-- --- PHẦN 3: SỬA LỖI TỌA ĐỘ (QUAN TRỌNG) ---

-- 5. Tạo VIEW (Bảng ảo) để chuyển đổi tọa độ sang JSON cho Web đọc
create or replace view tourist_locations_view as
select
  id,
  name,
  description,
  category,
  image_url,
  st_asgeojson(location)::json as location -- Phép thuật chuyển đổi ở đây
from tourist_spots;

-- 6. Cấp quyền truy cập cho VIEW này
alter view tourist_locations_view owner to postgres;
grant select on tourist_locations_view to anon, authenticated;