-- 1. Bật tính năng GIS (Quan trọng nhất)
create extension if not exists postgis;

-- 2. Tạo bảng địa điểm du lịch
create table tourist_spots (
  id bigint generated by default as identity primary key,
  name text not null,               -- Tên địa điểm (VD: Hồ Gươm)
  description text,                 -- Mô tả ngắn
  category text,                    -- Loại: 'culture', 'food', 'park'
  image_url text,                   -- Link ảnh
  location geography(POINT)         -- Cột lưu tọa độ (Kinh độ, Vĩ độ)
);

-- 3. Thêm dữ liệu mẫu (Hà Nội)
insert into tourist_spots (name, description, category, location)
values
  (
    'Hồ Gươm',
    'Trái tim của thủ đô Hà Nội, nơi có Tháp Rùa cổ kính.',
    'park',
    st_point(105.8521, 21.0285) -- Kinh độ, Vĩ độ
  ),
  (
    'Lăng Chủ tịch Hồ Chí Minh',
    'Nơi an nghỉ vĩnh hằng của Bác Hồ.',
    'culture',
    st_point(105.8342, 21.0368)
  ),
  (
    'Nhà thờ Lớn Hà Nội',
    'Công trình kiến trúc Pháp cổ kính.',
    'culture',
    st_point(105.8493, 21.0288)
  );

-- 4. Mở quyền truy cập (Để web và n8n có thể đọc dữ liệu)
alter table tourist_spots enable row level security;

create policy "Cho phép ai cũng xem được địa điểm"
on tourist_spots for select
to anon, authenticated
using (true);